[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi=true
ast = true
build_info = true
extra_output = ["storageLayout"]
solc_version = '0.8.26'    # Solidity compiler version
optimizer = true           # Enable optimizer
optimizer_runs = 200       # Optimizer runs
evm_version = 'cancun'   # EVM version

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
